version: "2"
services:
  bbnb_detail:
    container_name: bbnb_detail
    restart: always
    build: .
    ports:
      - "80:8000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
